"""empty message

Revision ID: 598d25c44ae9
Revises: None
Create Date: 2016-06-20 01:58:13.568693

"""

# revision identifiers, used by Alembic.
revision = '598d25c44ae9'
down_revision = None

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('adjective',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('adj', sa.String(length=50), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('name',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=50), nullable=True),
    sa.Column('adj_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['adj_id'], ['adjective.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('name')
    op.drop_table('adjective')
    ### end Alembic commands ###
